# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CONSCIOUSCODERS.blog
tagline:          'The Conscious Coders Blog'
description:      'On the impact of AI and digital technologies on society.'
url:              http://consciouscoders.io
baseurl:          /

author:
  name:           'Bubl'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gedachtes/gedachtes.github.io/
