# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ConsciousCoders Blog
tagline:          'ConsciousCoders Blog'
description:      'A blog about Ethical use of AI.'
url:              http://consciouscoders.io
baseurl:          /

author:
  name:           'Bubl'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gedachtes/gedachtes.github.io/
